# Generated by Django 4.0.5 on 2022-11-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
